name = "demashqi-restaurant-backend"
main = "backend/worker.js"
compatibility_date = "2024-11-01"
compatibility_flags = ["nodejs_compat"]

[vars]
# Add your Paymob and Stripe API Keys here via Cloudflare Dashboard or wrangler secret put

[[d1_databases]]
binding = "DB" # Available in your worker as env.DB
database_name = "demashqi-db"
database_id = "a4fe78eb-6ac4-434c-8c59-9831f687ced1"

[assets]
binding = "ASSETS"
directory = "dist"
